[gaps]
inner.horizontal = 20
inner.vertical = 20
outer.left = 20
outer.bottom = 20
outer.top = 20
outer.right = 20

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-0 = 'workspace 0:streaming'
alt-1 = 'workspace 1:web'
alt-2 = 'workspace 2:term'
alt-3 = 'workspace 3:ide'
alt-4 = 'workspace 4:devtools'
alt-5 = 'workspace 5:planning'
alt-6 = 'workspace 6:editing'
alt-7 = 'workspace 7:chat'
alt-8 = 'workspace 8:misc'

alt-shift-0 = 'move-node-to-workspace 0:streaming'
alt-shift-1 = 'move-node-to-workspace 1:web'
alt-shift-2 = 'move-node-to-workspace 2:term'
alt-shift-3 = 'move-node-to-workspace 3:ide'
alt-shift-4 = 'move-node-to-workspace 4:devtools'
alt-shift-5 = 'move-node-to-workspace 5:planning'
alt-shift-6 = 'move-node-to-workspace 6:editing'
alt-shift-7 = 'move-node-to-workspace 7:chat'
alt-shift-8 = 'move-node-to-workspace 8:misc'

alt-tab = 'workspace-back-and-forth'

alt-f = 'layout floating tiling'
alt-r = 'flatten-workspace-tree'
alt-w = 'close'
alt-shift-w = 'close-all-windows-but-current'

alt-semicolon = 'mode service'

[mode.service.binding]
esc = ['mode main']
r = 'reload-config'

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# Placements

# Streaming
[[on-window-detected]]
if.app-id = 'com.obsproject.obs-studio'
run = 'move-node-to-workspace 0:streaming'

# Web
[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 1:web'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 1:web'

# Terminals
[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = 'move-node-to-workspace 2:term'

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace 2:term'

# IDEs
[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 3:ide'

[[on-window-detected]]
if.app-id = 'com.apple.dt.Xcode'
run = 'move-node-to-workspace 3:ide'

# Dev tools
[[on-window-detected]]
if.app-id = 'com.docker.docker'
run = 'move-node-to-workspace 4:devtools'

[[on-window-detected]]
if.app-id = 'com.balsamiq.wireframes'
run = 'move-node-to-workspace 4:devtools'

[[on-window-detected]]
if.app-id = 'com.luckymarmot.Paw' # RapidAPI
run = 'move-node-to-workspace 4:devtools'

[[on-window-detected]]
if.app-id = 'com.tinyapp.TablePlus'
run = 'move-node-to-workspace 4:devtools'

# Planning
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 5:planning'

[[on-window-detected]]
if.app-id = 'com.omnigroup.OmniFocus3.MacAppStore'
run = 'move-node-to-workspace 5:planning'

[[on-window-detected]]
if.app-id = 'com.workflowy.desktop'
run = 'move-node-to-workspace 5:planning'

# Video and photo editing
[[on-window-detected]]
if.app-id = 'com.adobe.AfterEffects'
run = 'move-node-to-workspace 6:editing'

[[on-window-detected]]
if.app-id = 'com.adobe.Audition'
run = 'move-node-to-workspace 6:editing'

[[on-window-detected]]
if.app-id = 'com.adobe.Audition'
run = 'move-node-to-workspace 6:editing'

[[on-window-detected]]
if.app-id = 'com.adobe.illustrator'
run = 'move-node-to-workspace 6:editing'

[[on-window-detected]]
if.app-id = 'com.adobe.LightroomClassicCC7'
run = 'move-node-to-workspace 6:editing'

[[on-window-detected]]
if.app-id = 'com.adobe.Photoshop'
run = 'move-node-to-workspace 6:editing'

[[on-window-detected]]
if.app-id = 'com.adobe.PremierePro.24'
run = 'move-node-to-workspace 6:editing'

# Chat
[[on-window-detected]]
if.app-id = 'ai.elementlabs.lmstudio'
run = 'move-node-to-workspace 7:chat'

[[on-window-detected]]
if.app-id = 'com.quora.poe.electron'
run = 'move-node-to-workspace 7:chat'

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = 'move-node-to-workspace 7:chat'

[[on-window-detected]]
if.app-id = 'com.skype.skype'
run = 'move-node-to-workspace 7:chat'

[[on-window-detected]]
if.app-id = 'com.tdesktop.Telegram'
run = 'move-node-to-workspace 7:chat'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 7:chat'

# Misc
[[on-window-detected]]
if.app-id = 'com.jordanbaird.Ice'
run = 'move-node-to-workspace 8:misc'

[[on-window-detected]]
if.app-id = 'net.filebot.FileBot.pkg'
run = 'move-node-to-workspace 8:misc'

[[on-window-detected]]
if.app-id = 'com.nvidia.gfnpc.mall'
run = 'move-node-to-workspace 8:misc'

[[on-window-detected]]
if.app-id = 'org.keepassxc.keepassxc'
run = 'move-node-to-workspace 8:misc'
